[package]
name = "rust-subset-wgsl"
version = "0.1.0"
edition = "2021"

[dependencies]
gpu = { path = "gpu" }
gpu-macro = { path = "gpu-macro" }

# 根包 + 子 crate 组成一个 workspace(根包自动是成员)
[workspace]
members = ["gpu", "gpu-macro"]

[dev-dependencies]
naga = { version = "30.0.1", features = ["wgsl-in"] }
